{% set name = "google-cloud-core" %}
{% set version = "2.2.3" %}
{% set sha256 = "89d2f7189bc6dc74de128d423ea52cc8719f0a5dbccd9ca80433f6504a20255c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - google-api-core >=1.21.0,<2.0.0dev
    - google-auth >=1.24.0,<2.0.0dev
    # Support six==1.12.0 due to App Engine standard runtime.
    # https://github.com/googleapis/python-cloud-core/issues/45
    - six >=1.12.0
    - grpcio >=1.8.2,<2.0.0dev

test:
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation
  requires:
    - pip
    - python
  commands:
    - python -m pip check

about:
  home: https://github.com/googleapis/python-cloud-core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googleapis.dev/python/google-cloud-core/latest/
  dev_url: https://github.com/googleapis/python-cloud-core

extra:
  recipe-maintainers:
    - leahecole
    - parthea
    - tswast
