{% set name = "google-cloud-core" %}
{% set version = "0.27.1" %}
{% set sha256 = "1e52449feb72160a726798a085d7b0cf1d7b88d4b4af00f04d9ca9d6eb47847b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - googleapis-common-protos >=1.3.4
    - protobuf >=3.0.0
    - google-auth >=0.4.0,<2dev
    - requests >=2.18.0,<3.0.0dev
    - setuptools >=34.0.0
    - six >=1.10.0

test:
  imports:
    - google.cloud.client

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/core

extra:
  recipe-maintainers:
    - parthea
    - tswast
