{% set name = "google-cloud-core" %}
{% set version = "0.29.1" %}
{% set sha256 = "d85b1aaaf3bad9415ad1d8ee5eadce96d7007a82f13ce0a0629a003a11e83f29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - google-api-core >=0.1.1,<2.0.0dev

test:
  imports:
    - google.cloud.client

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googlecloudplatform.github.io/google-cloud-python/stable/google-cloud-api.html
  dev_url: https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/core

extra:
  recipe-maintainers:
    - parthea
    - tswast
