{% set name = "google-cloud-core" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_")  }}-{{ version }}.tar.gz
  sha256: 7c1b7ef5c92311717bd05301aa1a91ffbc565673d3b0b4163a52d8413a186963

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - google-api-core >=1.31.6,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0
    - importlib-metadata>1.0.0            # [py<38]
  run_constrained:
    - grpcio >=1.38.0,<2.0.0              # [py<314]
    - grpcio >=1.75.1,<2.0.0              # [py>=314]
    - grpcio-status >=1.38.0,<2.0.0

test:
  source_files:
    tests
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation
    - google.auth
    - google.cloud
    - google.longrunning
    - google.oauth2
    - google.protobuf
    - google.rpc
    - google.type
  requires:
    - pip
    - pytest
    - google-api-core >=1.31.6,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.25.0,<3.0.0
    - importlib-metadata>1.0.0            # [py<38]
    - grpcio >=1.38.0,<2.0.0              # [py<314]
    - grpcio >=1.75.1,<2.0.0              # [py>=314]
    - grpcio-status >=1.38.0,<2.0.0
  commands:
    - python -m pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv tests
#  downstreams:
#    - gensim
#    - google-cloud-storage

about:
  home: https://github.com/googleapis/python-cloud-core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: API Client library for Google Cloud Core Helpers
  description: |
    This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://cloud.google.com/python/docs/reference/google-cloud-core/latest
  dev_url: https://github.com/googleapis/python-cloud-core

extra:
  recipe-maintainers:
    - leahecole
    - parthea
    - tswast
