{% set name = "google-cloud-core" %}
{% set version = "2.3.2" %}
{% set sha256 = "b9529ee7047fd8d4bf4a2182de619154240df17fbe60ead399078c1ae152af9a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True #[py<37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - google-api-core >=1.31.6,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0",
    - google-auth >=1.25.0,<3.0.0dev
    - grpcio >=1.38.0,<2.0.0dev

test:
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation
  requires:
    - pip
  commands:
    - python -m pip check
#  downstreams:
#    - gensim
#    - google-cloud-storage

about:
  home: https://github.com/googleapis/python-cloud-core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://github.com/googleapis/python-cloud-core/blob/main/LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://cloud.google.com/python/docs/reference/google-cloud-core/latest
  dev_url: https://github.com/googleapis/python-cloud-core

extra:
  recipe-maintainers:
    - leahecole
    - parthea
    - tswast
