{% set name = "google-cloud-core" %}
{% set version = "1.2.0" %}
{% set sha256 = "4ae0f37ece5f3b5baf9fa5b79b23482cb43a0207e380b5476cd4bd18e3ddd06d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: "pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - google-api-core >=1.16.0,<2.0.0dev

test:
  imports:
    - google.api_core.client_info
    - google.cloud.client
    - google.cloud.environment_vars
    - google.cloud.exceptions
    - google.cloud.operation

about:
  home: https://github.com/googleapis/google-cloud-python/tree/master/core
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'API Client library for Google Cloud: Core Helpers'
  description: This library is not meant to stand-alone. Instead it defines common helpers
    (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
  doc_url: https://googleapis.dev/python/google-cloud-core/latest/
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/core

extra:
  recipe-maintainers:
    - leahecole
    - parthea
    - tswast
