travis:
  secure:
    BINSTAR_TOKEN: CeI4MHR62c2w3w7U/gRZ0PrcaIHviD7Sg6pbniS/TvdO4IL9AEy/ZMSYkRg4rfGpya4AVU3Ij1oLsFQUF44sjrUYZUHeObjiDgqV9znQR3v1zmiTc3QzIvoLSVby5gCt1DcQWdDgnqXXR6OVJVhM7RM/VYfVCy1vR4dYg2ZVvZ4YZosyz0x/vA8FgGfcgI9oe7Li4qri6QKvxwR+9kIlH5LdHNopYQIKXLxZTsSCIdfi1jQYoG1ozuzIiTa/m7FlUDgPkYjAOOc2/S70XO2jl1k1TH4mS/zUv9AFYXtbrCFJoZ7PTwr9R4Zo8pWQRQSCUAolKvjo9UANijsl70bWkiLDoKeYTqBY08Nk6MzbYrKa6Q4wNh06MJ8w16cJTw2MgEeiTtCUND2RzfBjTY7yyuK0zO7tum0V2Hy7jKyJb4LL4kICb6NhVwfGFTx3Qq48C2vjiNltRVPgFYK+tKVD6BmCB4d/6d/IVcIzD2u8iF2YuLyCROEZyPswWlKR3E48SpyU5YZlLmUURt2qyArqfHXlgg+OsranJXC1+3KbCU+Uyo+OhhML78+vDTBe+ExlmT1DAsrzBwGJeAihn5a3wwaDKcVzg43HwWe1IImY3TE0hBqFkTchdiqT1HQjdLfJ7kwZg1Qa5rsgAdgvfPH4innQC0gS5R81Ljk5TtZdW1c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
