travis:
  secure:
    BINSTAR_TOKEN: xszBBt2XctoR2VFYOmRHVoeweOufOiF3YX2hJmO7g5UcyurbppdQipiiPM7PK9x1AKQwjIEwx12c6O8+ghvlRTnFJSMHYLlsiJ0paZbwIqf2YB0kHMH/fei5l5S47dJfAYYsBu4tiw/luWmyWsH8L0UVPEjE3NEPcfg1TCi8T/yyy/+HnfFjLaqSi4ryX2/NU8nnTJ3i8E7a1siMQYFwQBRGnm8o8pvwo31MU5d78tDDfyPQSIviejADNseQlbztqlQVL3TL6mdfGzWhP7R5IRNU0cNHJUpic36AVi1EczDJvC5OL4ykCQMg3SeTFteRTZ2FxUhlWzzd0AmeMC6PASqYcDGpRV8zK0gbhh9MdSFZlWMDX4NXPQbwUHACz/9iday/4XWH/tvX4/l9IOIErMuCz3/kq/yoiL+TJv26xHYha/kO+loieUJoqPWHA7pAWsRWMBjMBTcffeRuT35vFVVHvtyBb8HQjJTZfVGar6+l3qMwfQ4Q7L0vS0HQcQM6CnIvox6/5P7LqGtj+5wiMsDNEvxrod4iLsJt53qJTUDv2gSwaDA6DpfZwVf6a023IzKZDJePLhUeG7sHNrjcgnEcd7p5b2KuyjWrc4Dat3R7RnDhHOuPyljFjbfWbQcJfdKAH2YzTRVJTeAikGQBaqeAmmIqnB04Nh5VdDbpXJM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
